/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elsordermanagementsystem;
//import cost.Description;
import Cost.Ingredient2;
import Cost.Description1;
import Cost.IngredientTable;
import Cost.Other;
import Cost.OtherTable;
import Cost.Sms1;
//import Cost.OtherCalculation1;
//import MyFrames.Description;
import MyFrames.AddNewJobFrame;
import MyFrames.DailyProductionFrame;
import MyFrames.DailyProductionProgress;
import MyFrames.DailyTargetFrame;
import MyFrames.JobUpdateForm;
import MyFrames.Mypanels.StockView;
import MyFrames.StockUpdateForm;
import MyFrames.ViewJobFrame;
import com.teknikindustries.sms.Sms;


public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnOnGoPro = new javax.swing.JButton();
        desktop1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        btnStock = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        desktop2 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        btnDaiTar = new javax.swing.JButton();
        btnDaiPro = new javax.swing.JButton();
        desktop3 = new javax.swing.JDesktopPane();
        btnProProg = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        description = new javax.swing.JButton();
        desktop4 = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        description1 = new javax.swing.JButton();
        Table = new javax.swing.JButton();
        desktop55 = new javax.swing.JDesktopPane();
        jPanel7 = new javax.swing.JPanel();
        description2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        desktop6 = new javax.swing.JDesktopPane();
        jPanel8 = new javax.swing.JPanel();
        description3 = new javax.swing.JButton();
        desktop7 = new javax.swing.JDesktopPane();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELS Order Management System");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("  ELS(PVT) LTD");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Order Management System");

        jTabbedPane1.setForeground(new java.awt.Color(0, 153, 153));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnAdd.setText("Add New");
        btnAdd.setPreferredSize(new java.awt.Dimension(235, 40));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnOnGoPro.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnOnGoPro.setText("Ongoing Projects");
        btnOnGoPro.setPreferredSize(new java.awt.Dimension(235, 40));
        btnOnGoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnGoProActionPerformed(evt);
            }
        });

        desktop1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout desktop1Layout = new javax.swing.GroupLayout(desktop1);
        desktop1.setLayout(desktop1Layout);
        desktop1Layout.setHorizontalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktop1Layout.setVerticalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOnGoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1387, Short.MAX_VALUE))
            .addComponent(desktop1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnOnGoPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Order Details", jPanel1);

        btnStock.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnStock.setText("Stock");
        btnStock.setToolTipText("");
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton2.setText("Job");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        desktop2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout desktop2Layout = new javax.swing.GroupLayout(desktop2);
        desktop2.setLayout(desktop2Layout);
        desktop2Layout.setHorizontalGroup(
            desktop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktop2Layout.setVerticalGroup(
            desktop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1387, Short.MAX_VALUE))
            .addComponent(desktop2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop2))
        );

        jTabbedPane1.addTab("Update", jPanel3);

        btnDaiTar.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnDaiTar.setText("Daily Target");
        btnDaiTar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaiTarActionPerformed(evt);
            }
        });

        btnDaiPro.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnDaiPro.setText("Daily Production");
        btnDaiPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaiProActionPerformed(evt);
            }
        });

        desktop3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout desktop3Layout = new javax.swing.GroupLayout(desktop3);
        desktop3.setLayout(desktop3Layout);
        desktop3Layout.setHorizontalGroup(
            desktop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktop3Layout.setVerticalGroup(
            desktop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );

        btnProProg.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnProProg.setText("Production Progress");
        btnProProg.setPreferredSize(new java.awt.Dimension(235, 40));
        btnProProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProProgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDaiTar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDaiPro, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1134, Short.MAX_VALUE))
            .addComponent(desktop3)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaiTar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDaiPro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProProg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop3))
        );

        jTabbedPane1.addTab("Reports", jPanel4);

        description.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        description.setText("Description");
        description.setToolTipText("");
        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });

        desktop4.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout desktop4Layout = new javax.swing.GroupLayout(desktop4);
        desktop4.setLayout(desktop4Layout);
        desktop4Layout.setHorizontalGroup(
            desktop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktop4Layout.setVerticalGroup(
            desktop4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1635, Short.MAX_VALUE))
            .addComponent(desktop4)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop4))
        );

        jTabbedPane3.addTab("Description", jPanel5);

        description1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        description1.setText("Table");
        description1.setToolTipText("");
        description1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                description1ActionPerformed(evt);
            }
        });

        Table.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        Table.setText("Ingredient");
        Table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableActionPerformed(evt);
            }
        });

        desktop55.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout desktop55Layout = new javax.swing.GroupLayout(desktop55);
        desktop55.setLayout(desktop55Layout);
        desktop55Layout.setHorizontalGroup(
            desktop55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktop55Layout.setVerticalGroup(
            desktop55Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Table, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(description1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1366, Short.MAX_VALUE))
            .addComponent(desktop55)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Table, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop55))
        );

        jTabbedPane3.addTab("Ingredient", jPanel6);

        description2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        description2.setText("Other Calculation");
        description2.setToolTipText("");
        description2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                description2ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton6.setText("Table");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        desktop6.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout desktop6Layout = new javax.swing.GroupLayout(desktop6);
        desktop6.setLayout(desktop6Layout);
        desktop6Layout.setHorizontalGroup(
            desktop6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktop6Layout.setVerticalGroup(
            desktop6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(description2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1382, Short.MAX_VALUE))
            .addComponent(desktop6)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop6))
        );

        jTabbedPane3.addTab("Other Calculation", jPanel7);

        description3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        description3.setText("SMS");
        description3.setToolTipText("");
        description3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                description3ActionPerformed(evt);
            }
        });

        desktop7.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout desktop7Layout = new javax.swing.GroupLayout(desktop7);
        desktop7.setLayout(desktop7Layout);
        desktop7Layout.setHorizontalGroup(
            desktop7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktop7Layout.setVerticalGroup(
            desktop7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(description3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1635, Short.MAX_VALUE))
            .addComponent(desktop7)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(description3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktop7))
        );

        jTabbedPane3.addTab("SMS", jPanel8);

        jTabbedPane1.addTab("cost calculate", jTabbedPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1892, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jLabel1.getAccessibleContext().setAccessibleName("ELS(PVT) LTD.");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        AddNewJobFrame jf = new AddNewJobFrame();
        desktop1.add(jf);
        jf.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnOnGoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnGoProActionPerformed
        ViewJobFrame vjf = new ViewJobFrame();
        desktop1.add(vjf);
        vjf.setVisible(true);
    }//GEN-LAST:event_btnOnGoProActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        StockUpdateForm suf = new StockUpdateForm();
        desktop2.add(suf);
        suf.setVisible(true);
    }//GEN-LAST:event_btnStockActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JobUpdateForm juf = new JobUpdateForm();
        desktop2.add(juf);
        juf.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDaiTarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaiTarActionPerformed
        DailyTargetFrame dtf = new DailyTargetFrame();
        desktop3.add(dtf);
        dtf.setVisible(true);
    }//GEN-LAST:event_btnDaiTarActionPerformed

    private void btnDaiProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaiProActionPerformed
        DailyProductionFrame dpf = new DailyProductionFrame();
        desktop3.add(dpf);
        dpf.setVisible(true);
    }//GEN-LAST:event_btnDaiProActionPerformed

    private void btnProProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProProgActionPerformed
        DailyProductionProgress dppp = new DailyProductionProgress();
        desktop3.add(dppp);
        dppp.setVisible(true);
    }//GEN-LAST:event_btnProProgActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed

        Description1 jfm = new Description1();
        desktop4.add(jfm);
        jfm.setVisible(true);
    }//GEN-LAST:event_descriptionActionPerformed

    private void description1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_description1ActionPerformed
      IngredientTable jfmpy = new IngredientTable();
        desktop55.add(jfmpy);
        jfmpy.setVisible(true);
    }//GEN-LAST:event_description1ActionPerformed

    private void TableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableActionPerformed
         Ingredient2 jfmpy = new Ingredient2();
        desktop55.add(jfmpy);
        jfmpy.setVisible(true);
    }//GEN-LAST:event_TableActionPerformed

    private void description2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_description2ActionPerformed
       Other nnn = new Other();
       desktop6.add(nnn);
       nnn.setVisible(true);
    }//GEN-LAST:event_description2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         OtherTable nnn = new OtherTable();
       desktop6.add(nnn);
       nnn.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void description3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_description3ActionPerformed
       Sms1 nn4 = new Sms1();
       desktop7.add(nn4);
       nn4.setVisible(true);
    }//GEN-LAST:event_description3ActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Table;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDaiPro;
    private javax.swing.JButton btnDaiTar;
    private javax.swing.JButton btnOnGoPro;
    private javax.swing.JButton btnProProg;
    private javax.swing.JButton btnStock;
    private javax.swing.JButton description;
    private javax.swing.JButton description1;
    private javax.swing.JButton description2;
    private javax.swing.JButton description3;
    private javax.swing.JDesktopPane desktop1;
    private javax.swing.JDesktopPane desktop2;
    private javax.swing.JDesktopPane desktop3;
    private javax.swing.JDesktopPane desktop4;
    private javax.swing.JDesktopPane desktop55;
    private javax.swing.JDesktopPane desktop6;
    private javax.swing.JDesktopPane desktop7;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
